<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->
<extension>
  <name>catch_error</name>
  <version>1.0.0</version>
  <packageID></packageID>
  <ProductID></ProductID>
  <date>18/02/17</date>
  <license>Proprietary</license>
  <description></description>
  <helpfile></helpfile>
  <installdir></installdir>
  <classname></classname>
  <androidclassname></androidclassname>
  <sourcedir></sourcedir>
  <androidsourcedir></androidsourcedir>
  <macsourcedir></macsourcedir>
  <maclinkerflags></maclinkerflags>
  <maccompilerflags></maccompilerflags>
  <androidinject></androidinject>
  <androidmanifestinject></androidmanifestinject>
  <iosplistinject></iosplistinject>
  <androidactivityinject></androidactivityinject>
  <gradleinject></gradleinject>
  <iosSystemFrameworks/>
  <iosThirdPartyFrameworks/>
  <ConfigOptions>
    <Config name="Default">
      <CopyToMask>113497714299118</CopyToMask>
    </Config>
  </ConfigOptions>
  <androidPermissions/>
  <IncludedResources>
    <Resource>Included Files\catch_error.html</Resource>
  </IncludedResources>
  <files>
    <file>
      <filename>catch_error.dll</filename>
      <origname>extensions\catch_error.dll</origname>
      <init></init>
      <final></final>
      <kind>1</kind>
      <uncompress>0</uncompress>
      <ConfigOptions>
        <Config name="Default">
          <CopyToMask>9223372036854775807</CopyToMask>
        </Config>
      </ConfigOptions>
      <ProxyFiles/>
      <functions>
        <function>
          <name>catch_error_set_normal_raw</name>
          <externalName>catch_error_set_normal_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>2</argCount>
          <args>
            <arg>1</arg>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_get_normal_raw</name>
          <externalName>catch_error_get_normal_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>2</argCount>
          <args>
            <arg>1</arg>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_set_fatal_raw</name>
          <externalName>catch_error_set_fatal_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>2</argCount>
          <args>
            <arg>1</arg>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_get_fatal_raw</name>
          <externalName>catch_error_get_fatal_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>2</argCount>
          <args>
            <arg>1</arg>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_set_prompt_raw</name>
          <externalName>catch_error_set_prompt_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>4</argCount>
          <args>
            <arg>1</arg>
            <arg>2</arg>
            <arg>1</arg>
            <arg>1</arg>
          </args>
        </function>
        <function>
          <name>catch_error_set_dump_path_raw</name>
          <externalName>catch_error_set_dump_path_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>3</argCount>
          <args>
            <arg>1</arg>
            <arg>2</arg>
            <arg>1</arg>
          </args>
        </function>
        <function>
          <name>catch_error_set_exec_raw</name>
          <externalName>catch_error_set_exec_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>4</argCount>
          <args>
            <arg>1</arg>
            <arg>2</arg>
            <arg>1</arg>
            <arg>1</arg>
          </args>
        </function>
        <function>
          <name>catch_error_get_prompt_kind</name>
          <externalName>catch_error_get_prompt_kind</externalName>
          <kind>1</kind>
          <help>catch_error_get_prompt_kind()</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_get_prompt_flags</name>
          <externalName>catch_error_get_prompt_flags</externalName>
          <kind>1</kind>
          <help>catch_error_get_prompt_flags()</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_get_prompt_text</name>
          <externalName>catch_error_get_prompt_text</externalName>
          <kind>1</kind>
          <help>catch_error_get_prompt_text()</help>
          <returnType>1</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_get_prompt_title</name>
          <externalName>catch_error_get_prompt_title</externalName>
          <kind>1</kind>
          <help>catch_error_get_prompt_title()</help>
          <returnType>1</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_get_dump_path</name>
          <externalName>catch_error_get_dump_path</externalName>
          <kind>1</kind>
          <help>catch_error_get_dump_path()</help>
          <returnType>1</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_dequeue</name>
          <externalName>catch_error_dequeue</externalName>
          <kind>1</kind>
          <help>catch_error_dequeue() : Returns you the next error from queue (or "" if empty)</help>
          <returnType>1</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_clear</name>
          <externalName>catch_error_clear</externalName>
          <kind>1</kind>
          <help>catch_error_clear() : Clears any queued error messages, returns how many there were</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_size</name>
          <externalName>catch_error_size</externalName>
          <kind>1</kind>
          <help>catch_error_size() : Returns the number of error messages in queue</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_get_exec_path</name>
          <externalName>catch_error_get_exec_path</externalName>
          <kind>1</kind>
          <help>catch_error_get_exec_path()</help>
          <returnType>1</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_get_exec_params</name>
          <externalName>catch_error_get_exec_params</externalName>
          <kind>1</kind>
          <help>catch_error_get_exec_params()</help>
          <returnType>1</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_fatal_force_raw</name>
          <externalName>catch_error_fatal_force_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_get_newer</name>
          <externalName>catch_error_get_newer</externalName>
          <kind>1</kind>
          <help>catch_error_get_newer()-&gt;catch_error_newer_*</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_set_newer_raw</name>
          <externalName>catch_error_set_newer_raw</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>1</argCount>
          <args>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_is_ready</name>
          <externalName>catch_error_is_ready</externalName>
          <kind>1</kind>
          <help>catch_error_is_ready()</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_is_loaded</name>
          <externalName>catch_error_is_loaded</externalName>
          <kind>1</kind>
          <help>catch_error_is_loaded() : returns whether the DLL successfully loaded as such</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_init</name>
          <externalName>catch_error_init</externalName>
          <kind>1</kind>
          <help>catch_error_init()</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
      </functions>
      <constants>
        <constant>
          <name>catch_error_normal_show</name>
          <value>0</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_normal_ignore</name>
          <value>1</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_normal_queue</name>
          <value>2</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_normal_quit</name>
          <value>3</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_fatal_show</name>
          <value>0</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_fatal_ignore</name>
          <value>1</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_fatal_queue</name>
          <value>2</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_fatal_quit</name>
          <value>3</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_prompt_none</name>
          <value>0</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_prompt_message</name>
          <value>1</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_prompt_question</name>
          <value>2</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_newer_not_ready</name>
          <value>-2</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_newer_unavailable</name>
          <value>-1</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_newer_allow</name>
          <value>0</value>
          <hidden>0</hidden>
        </constant>
        <constant>
          <name>catch_error_newer_ignore</name>
          <value>1</value>
          <hidden>0</hidden>
        </constant>
      </constants>
    </file>
    <file>
      <filename>catch_error.gml</filename>
      <origname>extensions\gml.gml</origname>
      <init></init>
      <final></final>
      <kind>2</kind>
      <uncompress>0</uncompress>
      <ConfigOptions>
        <Config name="Default">
          <CopyToMask>9223372036854775807</CopyToMask>
        </Config>
      </ConfigOptions>
      <ProxyFiles/>
      <functions>
        <function>
          <name>catch_error_prepare_buffer</name>
          <externalName>catch_error_prepare_buffer</externalName>
          <kind>11</kind>
          <help></help>
          <returnType>2</returnType>
          <argCount>1</argCount>
          <args>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_set_newer</name>
          <externalName>catch_error_set_newer</externalName>
          <kind>2</kind>
          <help>catch_error_set_newer(mode:catch_error_set_newer_*)</help>
          <returnType>2</returnType>
          <argCount>1</argCount>
          <args>
            <arg>2</arg>
          </args>
        </function>
      </functions>
      <constants/>
    </file>
    <file>
      <filename>autogen.gml</filename>
      <origname>extensions\autogen.gml</origname>
      <init></init>
      <final></final>
      <kind>2</kind>
      <uncompress>0</uncompress>
      <ConfigOptions>
        <Config name="Default">
          <CopyToMask>9223372036854775807</CopyToMask>
        </Config>
      </ConfigOptions>
      <ProxyFiles/>
      <functions>
        <function>
          <name>catch_error_set_normal</name>
          <externalName>catch_error_set_normal</externalName>
          <kind>2</kind>
          <help>catch_error_set_normal(catch_error_normal_:int)-&gt;bool</help>
          <returnType>2</returnType>
          <argCount>1</argCount>
          <args>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_get_normal</name>
          <externalName>catch_error_get_normal</externalName>
          <kind>2</kind>
          <help>catch_error_get_normal()-&gt;int</help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_set_fatal</name>
          <externalName>catch_error_set_fatal</externalName>
          <kind>2</kind>
          <help>catch_error_set_fatal(catch_error_fatal_:int)-&gt;bool</help>
          <returnType>2</returnType>
          <argCount>1</argCount>
          <args>
            <arg>2</arg>
          </args>
        </function>
        <function>
          <name>catch_error_get_fatal</name>
          <externalName>catch_error_get_fatal</externalName>
          <kind>2</kind>
          <help>catch_error_get_fatal()-&gt;int </help>
          <returnType>2</returnType>
          <argCount>0</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_set_prompt</name>
          <externalName>catch_error_set_prompt</externalName>
          <kind>2</kind>
          <help>catch_error_set_prompt(catch_error_prompt_:int, text:string = "", title:string = "", MSDN_MessageBox_type:int = -1)-&gt;bool</help>
          <returnType>2</returnType>
          <argCount>-1</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_set_dump_path</name>
          <externalName>catch_error_set_dump_path</externalName>
          <kind>2</kind>
          <help>catch_error_set_dump_path(path:string = "")-&gt;bool</help>
          <returnType>2</returnType>
          <argCount>-1</argCount>
          <args/>
        </function>
        <function>
          <name>catch_error_set_exec</name>
          <externalName>catch_error_set_exec</externalName>
          <kind>2</kind>
          <help>catch_error_set_exec(path:string = "", args:string = "")-&gt;bool</help>
          <returnType>2</returnType>
          <argCount>-1</argCount>
          <args/>
        </function>
      </functions>
      <constants/>
    </file>
  </files>
</extension>
